// Generated by Comline

import {
    Client,
    Server,
    Handshake,
    RuntimeError,
    resolveKind,
    DatagramFraming,
    type Codec,
    type Dispatch,
    type Framing,
    type Kind,
    type Reply,
    type Transport,
} from "./index.ts";

/** Canonical digest of the frozen IR this file was generated from — the
*  two ends of a connection must agree on it. */
export const IR_HASH = 0x6b347d4fa800b29fn;

export interface Message {
    body: string;
    seq: number;
}

export interface Rejected {
    reason: string;
}

export class RejectedError extends Error {
    static readonly ordinal = 0;
    constructor(readonly data: Rejected) {
        super("Rejected");
        this.name = "RejectedError";
    }
}

export interface ChatSendParams {
    text: string;
}

export interface ChatHistoryParams {
    limit: number;
}

export interface ChatNoteParams {
    text: string;
}

export interface Chat {
    /** @throws {RejectedError} */
    send(params: ChatSendParams): Promise<Message>;
    history(params: ChatHistoryParams): Promise<Message[]>;
    wipe(): Promise<void>;
    note(params: ChatNoteParams): Promise<void>;
}

export const CHAT_CALLS = ["send", "history", "wipe", "note"] as const;

export class ChatDispatcher implements Dispatch {
    constructor(private readonly impl: Chat) {}

    calls(): readonly string[] {
        return CHAT_CALLS;
    }

    async dispatch(call: Kind, params: Uint8Array, codec: Codec, reply: Reply): Promise<void> {
        switch (resolveKind(call, CHAT_CALLS)) {
            case 0: {
                const p = codec.decode<ChatSendParams>(params);
                try {
                    reply.ok(codec.encode((await this.impl.send(p)) ?? null));
                } catch (e) {
                    if (e instanceof RejectedError) { reply.err(RejectedError.ordinal, codec.encode(e.data)); return; }
                    throw e;
                }
                return;
            }
            case 1: {
                const p = codec.decode<ChatHistoryParams>(params);
                reply.ok(codec.encode((await this.impl.history(p)) ?? null));
                return;
            }
            case 2: {
                reply.ok(codec.encode((await this.impl.wipe()) ?? null));
                return;
            }
            case 3: {
                const p = codec.decode<ChatNoteParams>(params);
                await this.impl.note(p);
                return;
            }
            default:
                throw RuntimeError.unknownCall();
        }
    }
}

export class ChatClient {
    constructor(private readonly client: Client) {}

    static async connect(transport: Transport, codec: Codec, framing: Framing = new DatagramFraming()): Promise<ChatClient> {
        const hs = new Handshake({ irHash: IR_HASH, wireFormat: codec.name, framing: framing.name });
        return new ChatClient(await Client.connect(transport, codec, hs, framing));
    }

    async send(params: ChatSendParams): Promise<Message> {
        const env = await this.client.call({ id: 0, name: "send" }, params);
        if ("ok" in env) return this.client.codec.decode<Message>(env.ok);
        switch (env.err.id) {
            case RejectedError.ordinal:
                throw new RejectedError(this.client.codec.decode<Rejected>(env.err.body));
            default:
                throw RuntimeError.remote(env.err.id);
        }
    }

    async history(params: ChatHistoryParams): Promise<Message[]> {
        const env = await this.client.call({ id: 1, name: "history" }, params);
        if ("ok" in env) return this.client.codec.decode<Message[]>(env.ok);
        throw RuntimeError.remote(env.err.id);
    }

    async wipe(): Promise<void> {
        const env = await this.client.call({ id: 2, name: "wipe" }, null);
        if ("ok" in env) return;
        throw RuntimeError.remote(env.err.id);
    }

    async note(params: ChatNoteParams): Promise<void> {
        await this.client.notify({ id: 3, name: "note" }, params);
    }
}

export function serveChat(impl: Chat, transport: Transport, codec: Codec, framing: Framing = new DatagramFraming()): Promise<void> {
    const hs = new Handshake({ irHash: IR_HASH, wireFormat: codec.name, framing: framing.name });
    return new Server(new ChatDispatcher(impl), codec, framing).serveHandshaked(transport, hs);
}

